site :opscode

metadata

cookbook 'build-essential'
cookbook 'git'
cookbook 'apt'
cookbook 'rbenv'
cookbook 'vim'
cookbook 'couchbase'
cookbook 'java'
cookbook 'elasticsearch'
cookbook 'nginx'
cookbook 'mysql'
cookbook 'openssh'
