source 'http://api.berkshelf.com'

metadata

cookbook 'build-essential'
cookbook 'git'
cookbook 'apt'
cookbook 'rbenv', git: 'git://github.com/fnichol/chef-rbenv.git'
cookbook 'ruby_build'
cookbook 'vim'
cookbook 'couchbase'
cookbook 'java'
cookbook 'elasticsearch'
cookbook 'nginx'
cookbook 'mysql'
cookbook 'openssh'
