name             'smartengine'
maintainer       'Josh Williams'
maintainer_email 'joshw@firma8.com'
license          'All rights reserved'
description      'Installs/Configures rails4 with couchbase and elasticsearch'
version          '0.2.1'

depends 'git'
depends 'apt'
depends 'rbenv'
depends 'vim'
depends 'couchbase'
depends 'java'
depends 'elasticsearch'
depends 'nginx'
depends 'mysql'
depends 'openssh'
