name             'smartengine'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures rails4 with couch'
version          '0.1.1'

depends 'git'
depends 'apt'
depends 'rbenv'
depends 'vim'
depends 'couchbase'
depends 'java'
depends 'elasticsearch'
