name             'smartengine'
maintainer       'Josh Williams'
maintainer_email 'joshw@firma8.com'
license          'All rights reserved'
description      'Installs/Configures rails4 with couch'
version          '0.1.3'

depends 'git'
depends 'apt'
depends 'rbenv'
depends 'vim'
depends 'couchbase'
depends 'java'
depends 'elasticsearch'
